Including countries of each stop in Chuuchuu data

In [1]:
import pandas as pd

In [2]:
import_data = input("Should we import CSVs ? (Yes/No)")

if import_data =="Yes":
    data_stations = pd.read_csv("stations.csv",sep=";")#trainlain stations
    data_chuuchuu = pd.read_csv("delay_records_2026-02-26_to_2026-03-04.csv")

C:\Users\TE\AppData\Local\Temp\ipykernel_31356\116151920.py:4: DtypeWarning: Columns (8,17,18,20,24,36,37,39,41,46,48,56,57,59,60,61,62,63,64,65,68,69,71,72,75) have mixed types. Specify dtype option on import or set low_memory=False.
  data_stations = pd.read_csv("stations.csv",sep=";")#trainlain stations
C:\Users\TE\AppData\Local\Temp\ipykernel_31356\116151920.py:5: DtypeWarning: Columns (2,4) have mixed types. Specify dtype option on import or set low_memory=False.
  data_chuuchuu = pd.read_csv("delay_records_2026-02-26_to_2026-03-04.csv")

In [3]:
stations = data_stations
chuuchuu = data_chuuchuu

In [4]:
stations.head()

,id,name,slug,uic,uic8_sncf,latitude,longitude,parent_station_id,hub_id,country,...,info:ja,info:ko,info:pl,info:pt,info:ru,info:sv,info:tr,info:zh,normalised_code,iata_airport_code
0,1,Château-Arnoux – St-Auban,chateau-arnoux-st-auban,NaN,NaN,44.081790,6.001625,NaN,NaN,FR,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,urn:trainline:public:nloc:csv1,NaN
1,2,Château-Arnoux – St-Auban,chateau-arnoux-st-auban,8775123.0,87751230.0,44.061565,5.997373,1.0,NaN,FR,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,urn:trainline:public:nloc:csv2,NaN
2,3,Château-Arnoux Mairie,chateau-arnoux-mairie,8775122.0,87751222.0,44.063863,6.011248,1.0,NaN,FR,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,urn:trainline:public:nloc:csv3,NaN
3,4,Digne-les-Bains,digne-les-bains,NaN,NaN,44.350000,6.350000,NaN,NaN,FR,...,ディーニュ＝レ＝バン,디뉴레뱅,NaN,NaN,Динь-ле-Бен,NaN,NaN,迪涅萊班,urn:trainline:public:nloc:csv4,NaN
4,6,Digne-les-Bains,digne-les-bains,8775149.0,87751495.0,44.088710,6.222982,4.0,NaN,FR,...,ディーニュ＝レ＝バン,디뉴레뱅,NaN,NaN,Динь-ле-Бен,NaN,NaN,迪涅萊班,urn:trainline:public:nloc:csv6,NaN

In [5]:
chuuchuu.head()

,agency,routeType,routeNumber,date,deutscheBahnStopId,timestamp,originalRoute,originalStopId,stopName,arrival,...,arrivalPlatform,plannedArrivalPlatform,arrivalCancelled,departure,plannedDeparture,departureDelay,departurePlatform,plannedDeparturePlatform,departureCancelled,extra
0,NS,Sprinter,8148,2026-02-26,8400058,2026-02-25 04:51:47+00,Sprinter 8148,2992170,Amsterdam Centraal,2026-02-26 14:25:00+00,...,10a,10a,f,NaN,2026-02-26 14:25:00+00,NaN,10a,10a,f,"{""nsAgency"": ""IFF:NS"", ""unplanned"": false, ""fu..."
1,NS,Sprinter,8148,2026-02-26,8400059,2026-02-25 04:51:47+00,Sprinter 8148,2992236,Amsterdam Sloterdijk,2026-02-26 14:19:00+00,...,12,12,f,2026-02-26 14:19:00+00,2026-02-26 14:19:00+00,0.0,12,12,f,"{""nsAgency"": ""IFF:NS"", ""unplanned"": false, ""fu..."
2,NS,Sprinter,8148,2026-02-26,8400561,2026-02-25 04:51:47+00,Sprinter 8148,3065389,Schiphol Airport,2026-02-26 14:07:00+00,...,3,3,f,2026-02-26 14:09:00+00,2026-02-26 14:09:00+00,0.0,3,3,f,"{""nsAgency"": ""IFF:NS"", ""unplanned"": false, ""fu..."
3,NS,Sprinter,8148,2026-02-26,8400079,2026-02-25 04:51:47+00,Sprinter 8148,2860888,Amsterdam Lelylaan,2026-02-26 14:15:00+00,...,2,2,f,2026-02-26 14:15:00+00,2026-02-26 14:15:00+00,0.0,2,2,f,"{""nsAgency"": ""IFF:NS"", ""unplanned"": false, ""fu..."
4,NS,Sprinter,8148,2026-02-26,8400332,2026-02-25 04:51:47+00,Sprinter 8148,2993022,Hoofddorp,NaN,...,3,3,f,2026-02-26 14:02:00+00,2026-02-26 14:02:00+00,0.0,3,3,f,"{""nsAgency"": ""IFF:NS"", ""unplanned"": false, ""fu..."

In [6]:
stations["slug"]

0              chateau-arnoux-st-auban
1              chateau-arnoux-st-auban
2                chateau-arnoux-mairie
3                      digne-les-bains
4                      digne-les-bains
                     ...
70841    la-defense-grande-arche-rer-e
70842     paris-gare-de-lyon-noctilien
70843        les-mureaux-vigne-blanche
70844                  basel-st-johann
70845                  basel-st-johann
Name: slug, Length: 70846, dtype: object

In [7]:
print(len(stations["slug"]))

70846

In [8]:
len(stations["slug"].unique())

69964

In [9]:
stations_unique = stations.drop_duplicates(subset="slug", keep="first")

In [10]:
len(stations_unique["slug"].unique())

69964

In [11]:
# chuuchuu["stopName_slug"] = (
#     chuuchuu["stopName"]
#     .str.lower()
#     .str.replace(" ", "-", regex=False)
# )

In [12]:
chuuchuu["stopName_slug"] = (
    chuuchuu["stopName"]
    .str.normalize("NFKD")
    .str.encode("ascii", "ignore")
    .str.decode("utf-8")
    .str.lower()
    .str.strip()
    .str.replace(r"\s+", "-", regex=True)
)

In [13]:
chuuchuu["stopName_slug"]

0            amsterdam-centraal
1          amsterdam-sloterdijk
2              schiphol-airport
3            amsterdam-lelylaan
4                     hoofddorp
                   ...
6623158                uzhhorod
6623159                  zahony
6623160             nyiregyhaza
6623161                 szolnok
6623162                debrecen
Name: stopName_slug, Length: 6623163, dtype: object

In [14]:
chuuchuu_merge = chuuchuu.merge(
    stations_unique[["slug", "country"]],
    how="left",                       # keep all rows in chuuchuu
    left_on="stopName_slug",            # column in chuuchuu
    right_on="slug"         # column in uic_codes
)
chuuchuu_merge = chuuchuu_merge.drop(columns=["slug"])

In [15]:
# chuuchuu = chuuchuu.rename(columns={"Alphabetical code": "countryStop"})

In [16]:
print(len(chuuchuu))
print(len(chuuchuu_merge))

6623163
6623163

In [17]:
# print(len(chuuchuu["countryStop"].unique()))
# print(chuuchuu["countryStop"].unique())
print(len(chuuchuu_merge["country"].unique()))
print(chuuchuu_merge["country"].unique())

22
['NL' 'IT' nan 'BE' 'DE' 'FR' 'CH' 'DK' 'HU' 'AT' 'PL' 'HR' 'CZ' 'RS' 'SI'
 'UA' 'LU' 'ES' 'RO' 'SK' 'SE' 'LI']

In [18]:
country_counts = (
    chuuchuu_merge.groupby("country")
    .agg(parent_count=("agency", lambda x: x.notna().sum()))
    .reset_index()
)
display(country_counts)
print(country_counts["parent_count"].sum())

   country  parent_count
0       AT         34019
1       BE        183870
2       CH        411329
3       CZ          1789
4       DE       2314850
5       DK          1714
6       ES           260
7       FR        346780
8       HR           567
9       HU         85560
10      IT        590533
11      LI            23
12      LU          1873
13      NL        371970
14      PL         15039
15      RO          1017
16      RS            25
17      SE           197
18      SI          1267
19      SK           125
20      UA           162

4362969

In [19]:
chuuchuu_merge[chuuchuu_merge["country"].isna()]

,agency,routeType,routeNumber,date,deutscheBahnStopId,timestamp,originalRoute,originalStopId,stopName,arrival,...,arrivalCancelled,departure,plannedDeparture,departureDelay,departurePlatform,plannedDeparturePlatform,departureCancelled,extra,stopName_slug,country
46,NS,Intercity,3142,2026-02-26,8400319,2026-02-25 13:23:47+00,Intercity 3142,3670859,'s-Hertogenbosch,2026-02-27 11:54:00+00,...,f,2026-02-27 11:55:00+00,NaN,0.0,NaN,NaN,f,"{""nsAgency"": ""IFF:NS"", ""unplanned"": true, ""ful...",'s-hertogenbosch,NaN
81,NS,Sprinter,8637,2026-02-26,8400053,2026-02-25 13:31:47+00,Sprinter 8637,2992146,Alphen a/d Rijn,NaN,...,f,2026-02-27 12:10:00+00,2026-02-26 12:10:00+00,0.0,3,3,f,"{""nsAgency"": ""IFF:R-NET_NS"", ""unplanned"": fals...",alphen-a/d-rijn,NaN
127,NS,Intercity,3171,2026-02-26,8400319,2026-02-25 13:31:47+00,Intercity 3171,3670859,'s-Hertogenbosch,2026-02-27 19:06:00+00,...,f,2026-02-27 19:08:00+00,NaN,0.0,NaN,NaN,f,"{""nsAgency"": ""IFF:NS"", ""unplanned"": true, ""ful...",'s-hertogenbosch,NaN
136,NS,Stoptrein,2583,2026-02-26,8800062,2026-02-25 13:31:47+00,Stoptrein 2583,2993451,Heide (B),2026-02-27 11:45:00+00,...,f,2026-02-27 11:46:00+00,2026-02-26 11:46:00+00,0.0,NaN,NaN,f,"{""nsAgency"": ""IFF:NMBS"", ""unplanned"": false, ""...",heide-(b),NaN
145,NS,Intercity,3143,2026-02-26,8400319,2026-02-25 13:31:47+00,Intercity 3143,3670859,'s-Hertogenbosch,2026-02-27 12:06:00+00,...,f,2026-02-27 12:08:00+00,NaN,0.0,NaN,NaN,f,"{""nsAgency"": ""IFF:NS"", ""unplanned"": true, ""ful...",'s-hertogenbosch,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6623146,IT,IC,1963,2026-03-04,8300180,2026-03-05 16:25:51.205+00,IC 1963,S06900,FIRENZE CAMPO MARTE,2026-03-04 23:40:30+00,...,NaN,2026-03-04 23:50:00+00,2026-03-04 23:12:00+00,2280.0,4,4,NaN,"{""viaggiatrenoTripId"": ""S01700|1963|1772578800...",firenze-campo-marte,NaN
6623153,GTFSDE,RB,10643,2026-03-04,8003708,2026-03-05 23:45:45+00,RB27 10643,::stop01196956,Linz(Rhein),2026-03-04 23:44:00+00,...,f,NaN,2026-03-04 23:42:00+00,NaN,NaN,3,f,"{""unplanned"": false, ""originalTripId"": ""123912...",linz(rhein),NaN
6623155,GTFSDE,RB,10643,2026-03-04,8001858,2026-03-05 23:45:45+00,RB27 10643,de:07138:020005:71,Erpel(Rhein),2026-03-04 23:40:00+00,...,f,2026-03-04 23:41:00+00,2026-03-04 23:40:00+00,60.0,NaN,1,f,"{""unplanned"": false, ""originalTripId"": ""123912...",erpel(rhein),NaN
6623156,GTFSDE,RB,10643,2026-03-04,8000713,2026-03-05 23:45:45+00,RB27 10643,::stop01190262,Bad Honnef(Rhein),2026-03-04 23:34:00+00,...,f,2026-03-04 23:35:00+00,2026-03-04 23:32:00+00,180.0,NaN,2,f,"{""unplanned"": false, ""originalTripId"": ""123912...",bad-honnef(rhein),NaN
6623159,HU,Gy,7,2026-03-04,5500064,2026-03-06 00:17:14.701+00,Gy 7,1:005514175_4,Záhony,2026-03-06 00:08:00+00,...,NaN,2026-03-06 01:08:00+00,2026-03-05 00:20:00+00,89280.0,4,4,NaN,"{""tripId"": ""VHJpcDoxOjI5MjA0Nzgy"", ""routeName""...",zahony,NaN

In [20]:
len(chuuchuu_merge[chuuchuu_merge["country"].isna()])+country_counts["parent_count"].sum()

np.int64(6623163)

In [21]:
chuuchuu_merge_missing_countries = chuuchuu_merge[chuuchuu_merge["country"].isna()]
chuuchuu_merge_missing_countries.head()

,agency,routeType,routeNumber,date,deutscheBahnStopId,timestamp,originalRoute,originalStopId,stopName,arrival,...,arrivalCancelled,departure,plannedDeparture,departureDelay,departurePlatform,plannedDeparturePlatform,departureCancelled,extra,stopName_slug,country
46,NS,Intercity,3142,2026-02-26,8400319,2026-02-25 13:23:47+00,Intercity 3142,3670859,'s-Hertogenbosch,2026-02-27 11:54:00+00,...,f,2026-02-27 11:55:00+00,NaN,0.0,NaN,NaN,f,"{""nsAgency"": ""IFF:NS"", ""unplanned"": true, ""ful...",'s-hertogenbosch,NaN
81,NS,Sprinter,8637,2026-02-26,8400053,2026-02-25 13:31:47+00,Sprinter 8637,2992146,Alphen a/d Rijn,NaN,...,f,2026-02-27 12:10:00+00,2026-02-26 12:10:00+00,0.0,3,3,f,"{""nsAgency"": ""IFF:R-NET_NS"", ""unplanned"": fals...",alphen-a/d-rijn,NaN
127,NS,Intercity,3171,2026-02-26,8400319,2026-02-25 13:31:47+00,Intercity 3171,3670859,'s-Hertogenbosch,2026-02-27 19:06:00+00,...,f,2026-02-27 19:08:00+00,NaN,0.0,NaN,NaN,f,"{""nsAgency"": ""IFF:NS"", ""unplanned"": true, ""ful...",'s-hertogenbosch,NaN
136,NS,Stoptrein,2583,2026-02-26,8800062,2026-02-25 13:31:47+00,Stoptrein 2583,2993451,Heide (B),2026-02-27 11:45:00+00,...,f,2026-02-27 11:46:00+00,2026-02-26 11:46:00+00,0.0,NaN,NaN,f,"{""nsAgency"": ""IFF:NMBS"", ""unplanned"": false, ""...",heide-(b),NaN
145,NS,Intercity,3143,2026-02-26,8400319,2026-02-25 13:31:47+00,Intercity 3143,3670859,'s-Hertogenbosch,2026-02-27 12:06:00+00,...,f,2026-02-27 12:08:00+00,NaN,0.0,NaN,NaN,f,"{""nsAgency"": ""IFF:NS"", ""unplanned"": true, ""ful...",'s-hertogenbosch,NaN

In [22]:
# chuuchuu_merge_missing_countries = chuuchuu_merge_missing_countries.merge(
#     uic_codes[["Numerical code", "Alphabetical code"]],
#     how="left",                       # keep all rows in chuuchuu_merge_missing_countries
#     left_on="uicCodeStop",            # column in chuuchuu_merge_missing_countries
#     right_on="Numerical code"         # column in uic_codes
# )
# chuuchuu_merge_missing_countries = chuuchuu_merge_missing_countries.drop(columns=["Numerical code"])

# chuuchuu_merge_missing_countries["Alphabetical code"].unique()


# Alphabetical_code_counts = (
#     chuuchuu_merge_missing_countries.groupby("Alphabetical code")
#     .agg(parent_count=("agency", lambda x: x.notna().sum()))
#     .reset_index()
# )
# display(Alphabetical_code_counts)

In [23]:
chuuchuu_merge_missing_countries = chuuchuu_merge_missing_countries.drop(columns = ["country"])
chuuchuu_merge_missing_countries.head()

,agency,routeType,routeNumber,date,deutscheBahnStopId,timestamp,originalRoute,originalStopId,stopName,arrival,...,plannedArrivalPlatform,arrivalCancelled,departure,plannedDeparture,departureDelay,departurePlatform,plannedDeparturePlatform,departureCancelled,extra,stopName_slug
46,NS,Intercity,3142,2026-02-26,8400319,2026-02-25 13:23:47+00,Intercity 3142,3670859,'s-Hertogenbosch,2026-02-27 11:54:00+00,...,NaN,f,2026-02-27 11:55:00+00,NaN,0.0,NaN,NaN,f,"{""nsAgency"": ""IFF:NS"", ""unplanned"": true, ""ful...",'s-hertogenbosch
81,NS,Sprinter,8637,2026-02-26,8400053,2026-02-25 13:31:47+00,Sprinter 8637,2992146,Alphen a/d Rijn,NaN,...,3,f,2026-02-27 12:10:00+00,2026-02-26 12:10:00+00,0.0,3,3,f,"{""nsAgency"": ""IFF:R-NET_NS"", ""unplanned"": fals...",alphen-a/d-rijn
127,NS,Intercity,3171,2026-02-26,8400319,2026-02-25 13:31:47+00,Intercity 3171,3670859,'s-Hertogenbosch,2026-02-27 19:06:00+00,...,NaN,f,2026-02-27 19:08:00+00,NaN,0.0,NaN,NaN,f,"{""nsAgency"": ""IFF:NS"", ""unplanned"": true, ""ful...",'s-hertogenbosch
136,NS,Stoptrein,2583,2026-02-26,8800062,2026-02-25 13:31:47+00,Stoptrein 2583,2993451,Heide (B),2026-02-27 11:45:00+00,...,NaN,f,2026-02-27 11:46:00+00,2026-02-26 11:46:00+00,0.0,NaN,NaN,f,"{""nsAgency"": ""IFF:NMBS"", ""unplanned"": false, ""...",heide-(b)
145,NS,Intercity,3143,2026-02-26,8400319,2026-02-25 13:31:47+00,Intercity 3143,3670859,'s-Hertogenbosch,2026-02-27 12:06:00+00,...,NaN,f,2026-02-27 12:08:00+00,NaN,0.0,NaN,NaN,f,"{""nsAgency"": ""IFF:NS"", ""unplanned"": true, ""ful...",'s-hertogenbosch

In [24]:
if stations_unique["db_id"].dtype == "float64":
    stations_unique["db_id"] = stations_unique["db_id"].astype("Int64")
    stations_unique["db_id"] = stations_unique["db_id"].astype("str")

chuuchuu_merge_missing_countries["deutscheBahnStopId"] = chuuchuu_merge_missing_countries["deutscheBahnStopId"].astype("str")

chuuchuu_merge_missing_countries = chuuchuu_merge_missing_countries.merge(
    stations_unique[["db_id", "country"]],
    how="left",                       # keep all rows in chuuchuu_merge_missing_countries
    left_on="deutscheBahnStopId",            # column in chuuchuu_merge_missing_countries
    right_on="db_id"         # column in uic_codes
)
chuuchuu_merge_missing_countries = chuuchuu_merge_missing_countries.drop(columns=["db_id"])

C:\Users\TE\AppData\Local\Temp\ipykernel_31356\2496280623.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stations_unique["db_id"] = stations_unique["db_id"].astype("Int64")
C:\Users\TE\AppData\Local\Temp\ipykernel_31356\2496280623.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stations_unique["db_id"] = stations_unique["db_id"].astype("str")

In [25]:
chuuchuu_merge_missing_countries

,agency,routeType,routeNumber,date,deutscheBahnStopId,timestamp,originalRoute,originalStopId,stopName,arrival,...,arrivalCancelled,departure,plannedDeparture,departureDelay,departurePlatform,plannedDeparturePlatform,departureCancelled,extra,stopName_slug,country
0,NS,Intercity,3142,2026-02-26,8400319,2026-02-25 13:23:47+00,Intercity 3142,3670859,'s-Hertogenbosch,2026-02-27 11:54:00+00,...,f,2026-02-27 11:55:00+00,NaN,0.0,NaN,NaN,f,"{""nsAgency"": ""IFF:NS"", ""unplanned"": true, ""ful...",'s-hertogenbosch,NL
1,NS,Sprinter,8637,2026-02-26,8400053,2026-02-25 13:31:47+00,Sprinter 8637,2992146,Alphen a/d Rijn,NaN,...,f,2026-02-27 12:10:00+00,2026-02-26 12:10:00+00,0.0,3,3,f,"{""nsAgency"": ""IFF:R-NET_NS"", ""unplanned"": fals...",alphen-a/d-rijn,NL
2,NS,Intercity,3171,2026-02-26,8400319,2026-02-25 13:31:47+00,Intercity 3171,3670859,'s-Hertogenbosch,2026-02-27 19:06:00+00,...,f,2026-02-27 19:08:00+00,NaN,0.0,NaN,NaN,f,"{""nsAgency"": ""IFF:NS"", ""unplanned"": true, ""ful...",'s-hertogenbosch,NL
3,NS,Stoptrein,2583,2026-02-26,8800062,2026-02-25 13:31:47+00,Stoptrein 2583,2993451,Heide (B),2026-02-27 11:45:00+00,...,f,2026-02-27 11:46:00+00,2026-02-26 11:46:00+00,0.0,NaN,NaN,f,"{""nsAgency"": ""IFF:NMBS"", ""unplanned"": false, ""...",heide-(b),BE
4,NS,Intercity,3143,2026-02-26,8400319,2026-02-25 13:31:47+00,Intercity 3143,3670859,'s-Hertogenbosch,2026-02-27 12:06:00+00,...,f,2026-02-27 12:08:00+00,NaN,0.0,NaN,NaN,f,"{""nsAgency"": ""IFF:NS"", ""unplanned"": true, ""ful...",'s-hertogenbosch,NL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2260189,IT,IC,1963,2026-03-04,8300180,2026-03-05 16:25:51.205+00,IC 1963,S06900,FIRENZE CAMPO MARTE,2026-03-04 23:40:30+00,...,NaN,2026-03-04 23:50:00+00,2026-03-04 23:12:00+00,2280.0,4,4,NaN,"{""viaggiatrenoTripId"": ""S01700|1963|1772578800...",firenze-campo-marte,IT
2260190,GTFSDE,RB,10643,2026-03-04,8003708,2026-03-05 23:45:45+00,RB27 10643,::stop01196956,Linz(Rhein),2026-03-04 23:44:00+00,...,f,NaN,2026-03-04 23:42:00+00,NaN,NaN,3,f,"{""unplanned"": false, ""originalTripId"": ""123912...",linz(rhein),DE
2260191,GTFSDE,RB,10643,2026-03-04,8001858,2026-03-05 23:45:45+00,RB27 10643,de:07138:020005:71,Erpel(Rhein),2026-03-04 23:40:00+00,...,f,2026-03-04 23:41:00+00,2026-03-04 23:40:00+00,60.0,NaN,1,f,"{""unplanned"": false, ""originalTripId"": ""123912...",erpel(rhein),DE
2260192,GTFSDE,RB,10643,2026-03-04,8000713,2026-03-05 23:45:45+00,RB27 10643,::stop01190262,Bad Honnef(Rhein),2026-03-04 23:34:00+00,...,f,2026-03-04 23:35:00+00,2026-03-04 23:32:00+00,180.0,NaN,2,f,"{""unplanned"": false, ""originalTripId"": ""123912...",bad-honnef(rhein),DE
2260193,HU,Gy,7,2026-03-04,5500064,2026-03-06 00:17:14.701+00,Gy 7,1:005514175_4,Záhony,2026-03-06 00:08:00+00,...,NaN,2026-03-06 01:08:00+00,2026-03-05 00:20:00+00,89280.0,4,4,NaN,"{""tripId"": ""VHJpcDoxOjI5MjA0Nzgy"", ""routeName""...",zahony,HU

In [26]:
chuuchuu_merge_missing_countries["country"].unique()

array(['NL', 'BE', 'DK', 'DE', nan, 'LU', 'IT', 'CH', 'HU', 'AT', 'SE',
       'PL', 'FR', 'GB', 'CZ', 'SI', 'NO', 'ES', 'SK', 'UA', 'RO'],
      dtype=object)

In [27]:
new_country_counts = (
    chuuchuu_merge_missing_countries.groupby("country")
    .agg(parent_count=("agency", lambda x: x.notna().sum()))
    .reset_index()
)
display(new_country_counts)
print(new_country_counts["parent_count"].sum())

   country  parent_count
0       AT          8799
1       BE        115527
2       CH         29999
3       CZ          1267
4       DE       1164455
5       DK        317252
6       ES            25
7       FR        111284
8       GB           569
9       HU          6062
10      IT        100166
11      LU          8174
12      NL         13401
13      NO            24
14      PL          8651
15      RO             5
16      SE          1339
17      SI           116
18      SK            38
19      UA            14

1887167

In [28]:
chuuchuu_merge_missing_countries[chuuchuu_merge_missing_countries["country"].isna()]

,agency,routeType,routeNumber,date,deutscheBahnStopId,timestamp,originalRoute,originalStopId,stopName,arrival,...,arrivalCancelled,departure,plannedDeparture,departureDelay,departurePlatform,plannedDeparturePlatform,departureCancelled,extra,stopName_slug,country
80,DK,IC,70182,2026-02-26,8600506,2026-02-25 23:19:17.155+00,IC 70182,8600506,Aarup St.,2026-02-25 23:50:00+00,...,f,2026-02-25 23:50:00+00,2026-02-25 23:50:00+00,0.0,NaN,1,f,"{""operator"": ""DSB"", ""data_source"": ""dsb"", ""pro...",aarup-st.,NaN
92,DK,Re,74895,2026-02-26,8600798,2026-02-25 23:19:17.155+00,Re 74895,8600798,Høje Taastrup St.,NaN,...,f,2026-02-25 23:33:00+00,2026-02-25 23:33:00+00,0.0,NaN,4,f,"{""operator"": ""DSB"", ""data_source"": ""dsb"", ""pro...",hje-taastrup-st.,NaN
109,DK,Togbus,99388,2026-02-26,8650044,2026-02-25 23:19:17.155+00,Togbus,8650044,Langå St. (togbus),NaN,...,f,NaN,2026-02-25 23:32:00+00,NaN,NaN,NaN,f,"{""operator"": ""DSB"", ""data_source"": ""dsb"", ""pro...",langa-st.-(togbus),NaN
137,GTFSDE,S,23802,2026-02-26,8506194,2026-02-25 23:45:45+00,S 23802,::stop01149791,Berg(CH),2026-02-25 23:14:18+00,...,f,2026-02-25 23:15:00+00,2026-02-25 23:14:00+00,60.0,NaN,2,f,"{""unplanned"": false, ""originalTripId"": ""251285...",berg(ch),NaN
261,DK,IC,70182,2026-02-26,8600512,2026-02-26 00:02:39.601+00,IC 70182,8600512,Odense St.,2026-02-26 00:02:00+00,...,f,2026-02-26 00:04:00+00,2026-02-26 00:04:00+00,0.0,NaN,4,f,"{""operator"": ""DSB"", ""data_source"": ""dsb"", ""pro...",odense-st.,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2260161,HU,IC,78,2026-03-04,5310988,2026-03-05 11:49:20.537+00,IC 78,1:005310988_0,Strehaia Halta,2026-03-05 00:08:00+00,...,NaN,2026-03-05 00:09:00+00,2026-03-05 00:09:00+00,0.0,NaN,NaN,NaN,"{""tripId"": ""VHJpcDoxOjMwMDE4OTc1"", ""routeName""...",strehaia-halta,NaN
2260162,HU,IC,78,2026-03-04,5311140,2026-03-05 11:49:20.537+00,IC 78,1:005311140_0,Drobeta Tr.Severin,2026-03-05 01:26:00+00,...,NaN,2026-03-05 01:27:00+00,2026-03-05 01:27:00+00,0.0,NaN,NaN,NaN,"{""tripId"": ""VHJpcDoxOjMwMDE4OTc1"", ""routeName""...",drobeta-tr.severin,NaN
2260163,HU,IC,78,2026-03-04,5517822,2026-03-05 11:49:20.537+00,IC 78,1:005517822_B,Kétpó,2026-03-05 10:09:00+00,...,NaN,2026-03-05 10:10:00+00,2026-03-05 10:08:00+00,120.0,B,B,NaN,"{""tripId"": ""VHJpcDoxOjMwMDE4OTc1"", ""routeName""...",ketpo,NaN
2260165,IT,IC,1959,2026-03-04,8311775,2026-03-05 12:23:20.399+00,IC 1959,S11775,VILLA S.GIOVANNI MARE,2026-03-05 07:30:00+00,...,NaN,2026-03-05 07:50:00+00,2026-03-05 07:15:00+00,2100.0,NaN,NaN,NaN,"{""viaggiatrenoTripId"": ""S08409|1959|1772578800...",villa-s.giovanni-mare,NaN
2260188,IT,IC,1963,2026-03-04,8311775,2026-03-05 16:25:51.205+00,IC 1963,S11775,VILLA S.GIOVANNI MARE,2026-03-05 10:45:00+00,...,NaN,2026-03-05 11:05:00+00,2026-03-05 10:45:00+00,1200.0,NaN,NaN,NaN,"{""viaggiatrenoTripId"": ""S01700|1963|1772578800...",villa-s.giovanni-mare,NaN

In [29]:
chuuchuu_merge_missing_countries["agency"].unique()

array(['NS', 'DK', 'NMBS', 'GTFSDE', 'HU', 'IT', 'DB', 'PL', 'FR', 'EST',
       'SBB'], dtype=object)

In [30]:
agency_counts = (
    chuuchuu_merge_missing_countries.groupby("agency")
    .agg(parent_count=("agency", lambda x: x.notna().sum()))
    .reset_index()
)
display(agency_counts)
print(agency_counts["parent_count"].sum())

    agency  parent_count
0       DB         31512
1       DK        387232
2      EST           248
3       FR        127915
4   GTFSDE       1166586
5       HU        234078
6       IT        114865
7     NMBS        129192
8       NS         15453
9       PL         14355
10     SBB         38758

2260194