In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("delay_records_2026-02-26_to_2026-03-04.csv")

C:\Users\TE\AppData\Local\Temp\ipykernel_29316\4016970825.py:1: DtypeWarning: Columns (2,4) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv("delay_records_2026-02-26_to_2026-03-04.csv")

In [3]:
data

,agency,routeType,routeNumber,date,deutscheBahnStopId,timestamp,originalRoute,originalStopId,stopName,arrival,...,arrivalPlatform,plannedArrivalPlatform,arrivalCancelled,departure,plannedDeparture,departureDelay,departurePlatform,plannedDeparturePlatform,departureCancelled,extra
0,NS,Sprinter,8148,2026-02-26,8400058,2026-02-25 04:51:47+00,Sprinter 8148,2992170,Amsterdam Centraal,2026-02-26 14:25:00+00,...,10a,10a,f,NaN,2026-02-26 14:25:00+00,NaN,10a,10a,f,"{""nsAgency"": ""IFF:NS"", ""unplanned"": false, ""fu..."
1,NS,Sprinter,8148,2026-02-26,8400059,2026-02-25 04:51:47+00,Sprinter 8148,2992236,Amsterdam Sloterdijk,2026-02-26 14:19:00+00,...,12,12,f,2026-02-26 14:19:00+00,2026-02-26 14:19:00+00,0.0,12,12,f,"{""nsAgency"": ""IFF:NS"", ""unplanned"": false, ""fu..."
2,NS,Sprinter,8148,2026-02-26,8400561,2026-02-25 04:51:47+00,Sprinter 8148,3065389,Schiphol Airport,2026-02-26 14:07:00+00,...,3,3,f,2026-02-26 14:09:00+00,2026-02-26 14:09:00+00,0.0,3,3,f,"{""nsAgency"": ""IFF:NS"", ""unplanned"": false, ""fu..."
3,NS,Sprinter,8148,2026-02-26,8400079,2026-02-25 04:51:47+00,Sprinter 8148,2860888,Amsterdam Lelylaan,2026-02-26 14:15:00+00,...,2,2,f,2026-02-26 14:15:00+00,2026-02-26 14:15:00+00,0.0,2,2,f,"{""nsAgency"": ""IFF:NS"", ""unplanned"": false, ""fu..."
4,NS,Sprinter,8148,2026-02-26,8400332,2026-02-25 04:51:47+00,Sprinter 8148,2993022,Hoofddorp,NaN,...,3,3,f,2026-02-26 14:02:00+00,2026-02-26 14:02:00+00,0.0,3,3,f,"{""nsAgency"": ""IFF:NS"", ""unplanned"": false, ""fu..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6623158,HU,Gy,7,2026-03-04,2238100,2026-03-06 00:17:14.701+00,Gy 7,1:002238100_0,Uzhhorod,2026-03-04 21:29:00+00,...,NaN,NaN,NaN,2026-03-04 21:29:00+00,2026-03-04 21:29:00+00,0.0,NaN,NaN,NaN,"{""tripId"": ""VHJpcDoxOjI5MjA0Nzgy"", ""routeName""..."
6623159,HU,Gy,7,2026-03-04,5500064,2026-03-06 00:17:14.701+00,Gy 7,1:005514175_4,Záhony,2026-03-06 00:08:00+00,...,4,4,NaN,2026-03-06 01:08:00+00,2026-03-05 00:20:00+00,89280.0,4,4,NaN,"{""tripId"": ""VHJpcDoxOjI5MjA0Nzgy"", ""routeName""..."
6623160,HU,Gy,7,2026-03-04,5500061,2026-03-06 00:17:14.701+00,Gy 7,1:005514019_2,Nyíregyháza,2026-03-06 01:52:00+00,...,2,NaN,NaN,2026-03-06 01:54:00+00,2026-03-05 01:06:00+00,89280.0,2,NaN,NaN,"{""tripId"": ""VHJpcDoxOjI5MjA0Nzgy"", ""routeName""..."
6623161,HU,Gy,7,2026-03-04,5500053,2026-03-06 00:17:14.701+00,Gy 7,1:005513748_1PJb,Szolnok,2026-03-06 02:46:00+00,...,1/b,1/b,NaN,2026-03-06 02:46:00+00,2026-03-05 02:57:00+00,85740.0,1/b,1/b,NaN,"{""tripId"": ""VHJpcDoxOjI5MjA0Nzgy"", ""routeName""..."
6623162,HU,Gy,7,2026-03-04,5500058,2026-03-06 00:17:14.701+00,Gy 7,1:005513912_4,Debrecen,2026-03-06 02:27:00+00,...,4,4,NaN,2026-03-06 02:29:00+00,2026-03-05 01:41:00+00,89280.0,4,4,NaN,"{""tripId"": ""VHJpcDoxOjI5MjA0Nzgy"", ""routeName""..."

In [4]:
data.head(5)

,agency,routeType,routeNumber,date,deutscheBahnStopId,timestamp,originalRoute,originalStopId,stopName,arrival,...,arrivalPlatform,plannedArrivalPlatform,arrivalCancelled,departure,plannedDeparture,departureDelay,departurePlatform,plannedDeparturePlatform,departureCancelled,extra
0,NS,Sprinter,8148,2026-02-26,8400058,2026-02-25 04:51:47+00,Sprinter 8148,2992170,Amsterdam Centraal,2026-02-26 14:25:00+00,...,10a,10a,f,NaN,2026-02-26 14:25:00+00,NaN,10a,10a,f,"{""nsAgency"": ""IFF:NS"", ""unplanned"": false, ""fu..."
1,NS,Sprinter,8148,2026-02-26,8400059,2026-02-25 04:51:47+00,Sprinter 8148,2992236,Amsterdam Sloterdijk,2026-02-26 14:19:00+00,...,12,12,f,2026-02-26 14:19:00+00,2026-02-26 14:19:00+00,0.0,12,12,f,"{""nsAgency"": ""IFF:NS"", ""unplanned"": false, ""fu..."
2,NS,Sprinter,8148,2026-02-26,8400561,2026-02-25 04:51:47+00,Sprinter 8148,3065389,Schiphol Airport,2026-02-26 14:07:00+00,...,3,3,f,2026-02-26 14:09:00+00,2026-02-26 14:09:00+00,0.0,3,3,f,"{""nsAgency"": ""IFF:NS"", ""unplanned"": false, ""fu..."
3,NS,Sprinter,8148,2026-02-26,8400079,2026-02-25 04:51:47+00,Sprinter 8148,2860888,Amsterdam Lelylaan,2026-02-26 14:15:00+00,...,2,2,f,2026-02-26 14:15:00+00,2026-02-26 14:15:00+00,0.0,2,2,f,"{""nsAgency"": ""IFF:NS"", ""unplanned"": false, ""fu..."
4,NS,Sprinter,8148,2026-02-26,8400332,2026-02-25 04:51:47+00,Sprinter 8148,2993022,Hoofddorp,NaN,...,3,3,f,2026-02-26 14:02:00+00,2026-02-26 14:02:00+00,0.0,3,3,f,"{""nsAgency"": ""IFF:NS"", ""unplanned"": false, ""fu..."

In [5]:
DB = data[data["agency"]=="DB"]
DB.head(5)

,agency,routeType,routeNumber,date,deutscheBahnStopId,timestamp,originalRoute,originalStopId,stopName,arrival,...,arrivalPlatform,plannedArrivalPlatform,arrivalCancelled,departure,plannedDeparture,departureDelay,departurePlatform,plannedDeparturePlatform,departureCancelled,extra
2901,DB,IR,3393,2026-02-26,8504414,2026-02-26 00:11:47.283+00,IR 3393,8504414,Lyss,2026-02-25 23:28:00+00,...,1,1,NaN,2026-02-25 23:30:00+00,2026-02-25 23:30:00+00,0.0,1,1,NaN,"{""arrivalPrognosisType"": null, ""departureProgn..."
2902,DB,IR,3393,2026-02-26,8507000,2026-02-26 00:11:47.283+00,IR 3393,8507000,Bern,NaN,...,9,9,NaN,2026-02-25 23:12:00+00,2026-02-25 23:12:00+00,0.0,9,9,NaN,"{""arrivalPrognosisType"": null, ""departureProgn..."
2903,DB,IR,3393,2026-02-26,8504300,2026-02-26 00:11:47.283+00,IR 3393,8504300,Biel/Bienne,2026-02-25 23:39:00+00,...,7,7,NaN,NaN,NaN,NaN,7,7,NaN,"{""arrivalPrognosisType"": null, ""departureProgn..."
3622,DB,IR,1842,2026-02-26,8501303,2026-02-26 00:20:56.635+00,IR 1842,8501303,Villeneuve(CH),NaN,...,1,2,NaN,2026-02-25 23:19:00+00,2026-02-25 23:19:00+00,0.0,1,2,NaN,"{""arrivalPrognosisType"": null, ""departureProgn..."
3623,DB,IR,1842,2026-02-26,8501300,2026-02-26 00:20:56.635+00,IR 1842,8501300,Montreux,2026-02-25 23:24:00+00,...,1,1,NaN,2026-02-25 23:25:00+00,2026-02-25 23:25:00+00,0.0,1,1,NaN,"{""arrivalPrognosisType"": null, ""departureProgn..."

In [6]:
DB["routeType"].unique()

array(['IR', 'IC', 'RJ', 'ICE', nan, 'BUS', 'D', 'EC', 'RJX', 'S', 'REX',
       'TGV', 'EST', 'RE', 'EN', 'WB', 'ECE', 'FLX', 'R', 'NJ', 'ES',
       'UEX'], dtype=object)

BUS? Is that Flxbus? If so, what is FLX ? 

WB = Westbahn I guess


Do they have a way to calculate distances? otherwise, depending on our need, might be interesting to integrate Gmaps API


Do they have a way to filter for long distances?

In [15]:
data[data["originalRoute"]=="Sprinter 8148"]

,agency,routeType,routeNumber,date,deutscheBahnStopId,timestamp,originalRoute,originalStopId,stopName,arrival,...,arrivalPlatform,plannedArrivalPlatform,arrivalCancelled,departure,plannedDeparture,departureDelay,departurePlatform,plannedDeparturePlatform,departureCancelled,extra
0,NS,Sprinter,8148,2026-02-26,8400058,2026-02-25 04:51:47+00,Sprinter 8148,2992170,Amsterdam Centraal,2026-02-26 14:25:00+00,...,10a,10a,f,NaN,2026-02-26 14:25:00+00,NaN,10a,10a,f,"{""nsAgency"": ""IFF:NS"", ""unplanned"": false, ""fu..."
1,NS,Sprinter,8148,2026-02-26,8400059,2026-02-25 04:51:47+00,Sprinter 8148,2992236,Amsterdam Sloterdijk,2026-02-26 14:19:00+00,...,12,12,f,2026-02-26 14:19:00+00,2026-02-26 14:19:00+00,0.0,12,12,f,"{""nsAgency"": ""IFF:NS"", ""unplanned"": false, ""fu..."
2,NS,Sprinter,8148,2026-02-26,8400561,2026-02-25 04:51:47+00,Sprinter 8148,3065389,Schiphol Airport,2026-02-26 14:07:00+00,...,3,3,f,2026-02-26 14:09:00+00,2026-02-26 14:09:00+00,0.0,3,3,f,"{""nsAgency"": ""IFF:NS"", ""unplanned"": false, ""fu..."
3,NS,Sprinter,8148,2026-02-26,8400079,2026-02-25 04:51:47+00,Sprinter 8148,2860888,Amsterdam Lelylaan,2026-02-26 14:15:00+00,...,2,2,f,2026-02-26 14:15:00+00,2026-02-26 14:15:00+00,0.0,2,2,f,"{""nsAgency"": ""IFF:NS"", ""unplanned"": false, ""fu..."
4,NS,Sprinter,8148,2026-02-26,8400332,2026-02-25 04:51:47+00,Sprinter 8148,2993022,Hoofddorp,NaN,...,3,3,f,2026-02-26 14:02:00+00,2026-02-26 14:02:00+00,0.0,3,3,f,"{""nsAgency"": ""IFF:NS"", ""unplanned"": false, ""fu..."
3848630,NS,Sprinter,8148,2026-03-02,8400561,2026-03-02 12:35:47+00,Sprinter 8148,3065389,Schiphol Airport,2026-03-02 14:07:00+00,...,3,3,f,2026-03-02 14:09:00+00,2026-03-02 14:09:00+00,0.0,3,3,f,"{""nsAgency"": ""IFF:NS"", ""unplanned"": false, ""fu..."
3848634,NS,Sprinter,8148,2026-03-02,8400332,2026-03-02 12:35:47+00,Sprinter 8148,2993022,Hoofddorp,NaN,...,3,3,f,2026-03-02 14:02:00+00,2026-03-02 14:02:00+00,0.0,3,3,f,"{""nsAgency"": ""IFF:NS"", ""unplanned"": false, ""fu..."
3849443,NS,Sprinter,8148,2026-03-02,8400059,2026-03-02 12:35:47+00,Sprinter 8148,2992236,Amsterdam Sloterdijk,2026-03-02 14:19:00+00,...,12,12,f,2026-03-02 14:19:00+00,2026-03-02 14:19:00+00,0.0,12,12,f,"{""nsAgency"": ""IFF:NS"", ""unplanned"": false, ""fu..."
3849446,NS,Sprinter,8148,2026-03-02,8400058,2026-03-02 12:35:47+00,Sprinter 8148,2992179,Amsterdam Centraal,2026-03-02 14:25:00+00,...,14a,14a,f,NaN,2026-03-02 14:25:00+00,NaN,14a,14a,f,"{""nsAgency"": ""IFF:NS"", ""unplanned"": false, ""fu..."
3849450,NS,Sprinter,8148,2026-03-02,8400079,2026-03-02 12:35:47+00,Sprinter 8148,2860888,Amsterdam Lelylaan,2026-03-02 14:15:00+00,...,2,2,f,2026-03-02 14:15:00+00,2026-03-02 14:15:00+00,0.0,2,2,f,"{""nsAgency"": ""IFF:NS"", ""unplanned"": false, ""fu..."
5021303,NS,Sprinter,8148,2026-03-03,8400561,2026-03-03 15:17:47+00,Sprinter 8148,3065389,Schiphol Airport,2026-03-03 14:07:00+00,...,3,3,f,2026-03-03 14:09:00+00,2026-03-03 14:09:00+00,0.0,3,3,f,"{""nsAgency"": ""IFF:NS"", ""unplanned"": false, ""fu..."
5021304,NS,Sprinter,8148,2026-03-03,8400332,2026-03-03 15:17:47+00,Sprinter 8148,2993022,Hoofddorp,NaN,...,3,3,f,2026-03-03 14:03:08+00,2026-03-03 14:02:00+00,68.0,3,3,f,"{""nsAgency"": ""IFF:NS"", ""unplanned"": false, ""fu..."
5021305,NS,Sprinter,8148,2026-03-03,8400079,2026-03-03 15:17:47+00,Sprinter 8148,2860888,Amsterdam Lelylaan,2026-03-03 14:15:50+00,...,2,2,f,2026-03-03 14:15:50+00,2026-03-03 14:15:00+00,50.0,2,2,f,"{""nsAgency"": ""IFF:NS"", ""unplanned"": false, ""fu..."
5021306,NS,Sprinter,8148,2026-03-03,8400059,2026-03-03 15:17:47+00,Sprinter 8148,2992236,Amsterdam Sloterdijk,2026-03-03 14:19:51+00,...,12,12,f,2026-03-03 14:19:51+00,2026-03-03 14:19:00+00,51.0,12,12,f,"{""nsAgency"": ""IFF:NS"", ""unplanned"": false, ""fu..."
5021307,NS,Sprinter,8148,2026-03-03,8400058,2026-03-03 15:17:47+00,Sprinter 8148,2992179,Amsterdam Centraal,2026-03-03 14:25:23+00,...,14a,14a,f,NaN,2026-03-03 14:25:00+00,NaN,14a,14a,f,"{""nsAgency"": ""IFF:NS"", ""unplanned"": false, ""fu..."
6143090,NS,Sprinter,8148,2026-03-04,8400561,2026-03-04 15:20:47+00,Sprinter 8148,3065389,Schiphol Airport,2026-03-04 14:07:00+00,...,3,3,f,2026-03-04 14:09:00+00,2026-03-04 14:09:00+00,0.0,3,3,f,"{""nsAgency"": ""IFF:NS"", ""unplanned"": false, ""fu..."
6143093,NS,Sprinter,8148,2026-03-04,8400332,2026-03-04 15:20:47+00,Sprinter 8148,2993022,Hoofddorp,NaN,...,3,3,f,2026-03-04 14:02:00+00,2026-03-04 14:02:00+00,0.0,3,3,f,"{""nsAgency"": ""IFF:NS"", ""unplanned"": false, ""fu..."
6143094,NS,Sprinter,8148,2026-03-04,8400079,2026-03-04 15:20:47+00,Sprinter 8148,2860888,Amsterdam Lelylaan,2026-03-04 14:15:00+00,...,2,2,f,2026-03-04 14:15:00+00,2026-03-04 14:15:00+00,0.0,2,2,f,"{""nsAgency"": ""IFF:NS"", ""unplanned"": false, ""fu..."
6143095,NS,Sprinter,8148,2026-03-04,8400059,2026-03-04 15:20:47+00,Sprinter 8148,2992236,Amsterdam Sloterdijk,2026-03-04 14:19:00+00,...,12,12,f,2026-03-04 14:19:00+00,2026-03-04 14:19:00+00,0.0,12,12,f,"{""nsAgency"": ""IFF:NS"", ""unplanned"": false, ""fu..."
6143394,NS,Sprinter,8148,2026-03-04,8400058,2026-03-04 15:20:47+00,Sprinter 8148,2992179,Amsterdam Centraal,2026-03-04 14:25:00+00,...,14a,14a,f,NaN,2026-03-04 14:25:00+00,NaN,14a,14a,f,"{""nsAgency"": ""IFF:NS"", ""unplanned"": false, ""fu..."

In [12]:
data[(data["originalRoute"]=="Sprinter 8148") & (data["date"]=="2026-02-26")]

,agency,routeType,routeNumber,date,deutscheBahnStopId,timestamp,originalRoute,originalStopId,stopName,arrival,...,arrivalPlatform,plannedArrivalPlatform,arrivalCancelled,departure,plannedDeparture,departureDelay,departurePlatform,plannedDeparturePlatform,departureCancelled,extra
0,NS,Sprinter,8148,2026-02-26,8400058,2026-02-25 04:51:47+00,Sprinter 8148,2992170,Amsterdam Centraal,2026-02-26 14:25:00+00,...,10a,10a,f,NaN,2026-02-26 14:25:00+00,NaN,10a,10a,f,"{""nsAgency"": ""IFF:NS"", ""unplanned"": false, ""fu..."
1,NS,Sprinter,8148,2026-02-26,8400059,2026-02-25 04:51:47+00,Sprinter 8148,2992236,Amsterdam Sloterdijk,2026-02-26 14:19:00+00,...,12,12,f,2026-02-26 14:19:00+00,2026-02-26 14:19:00+00,0.0,12,12,f,"{""nsAgency"": ""IFF:NS"", ""unplanned"": false, ""fu..."
2,NS,Sprinter,8148,2026-02-26,8400561,2026-02-25 04:51:47+00,Sprinter 8148,3065389,Schiphol Airport,2026-02-26 14:07:00+00,...,3,3,f,2026-02-26 14:09:00+00,2026-02-26 14:09:00+00,0.0,3,3,f,"{""nsAgency"": ""IFF:NS"", ""unplanned"": false, ""fu..."
3,NS,Sprinter,8148,2026-02-26,8400079,2026-02-25 04:51:47+00,Sprinter 8148,2860888,Amsterdam Lelylaan,2026-02-26 14:15:00+00,...,2,2,f,2026-02-26 14:15:00+00,2026-02-26 14:15:00+00,0.0,2,2,f,"{""nsAgency"": ""IFF:NS"", ""unplanned"": false, ""fu..."
4,NS,Sprinter,8148,2026-02-26,8400332,2026-02-25 04:51:47+00,Sprinter 8148,2993022,Hoofddorp,NaN,...,3,3,f,2026-02-26 14:02:00+00,2026-02-26 14:02:00+00,0.0,3,3,f,"{""nsAgency"": ""IFF:NS"", ""unplanned"": false, ""fu..."

In [17]:
data["deutscheBahnStopId"].describe()

count     6623163
unique      33063
top       8011162
freq         9767
Name: deutscheBahnStopId, dtype: object

In [20]:
data["deutscheBahnStopId"].isna().sum()

np.int64(0)

In [22]:
data["deutscheBahnStopId"].unique()

array(['8400058', '8400059', '8400561', ..., 646550, 8005920, '57208_2_1'],
      dtype=object)

In [28]:
print(len(data.columns))
print(data.columns)

22
Index(['agency', 'routeType', 'routeNumber', 'date', 'deutscheBahnStopId',
       'timestamp', 'originalRoute', 'originalStopId', 'stopName', 'arrival',
       'plannedArrival', 'arrivalDelay', 'arrivalPlatform',
       'plannedArrivalPlatform', 'arrivalCancelled', 'departure',
       'plannedDeparture', 'departureDelay', 'departurePlatform',
       'plannedDeparturePlatform', 'departureCancelled', 'extra'],
      dtype='object')